### ISSUE TITLE
npm i @fortawesome/free-brands-svg-icons

### ISSUE THREAD

**Issue by neuroflip** [Vhrollout/little-restro#3]
I'm peer-reviewing it (at coursera) and it does not compile in a fresh install because @fortawesome/free-brands-svg-icons must to be added in package.json. So add it using:

`npm i @fortawesome/free-brands-svg-icons`

**Comment by neuroflip** [comment]
`npm i --save @fortawesome/free-brands-svg-icons` 
`npm i --save @fortawesome/react-fontawesome`
`npm i --save @fortawesome/free-solid-svg-icons`

then the project compiles,
btw, this is a reuse of the previous Portfolio project... so bad.

**Comment by Vhrollout** [comment]
Thanx for the suggestion, but I didn't use any previous project. I hard
coded all the stuff. It was my first attempt. Thanks again for honest
advice.

**Comment by neuroflip** [comment]
🙏🙏🙏🙏 My apologizes for that so sharp comment. I was confused with other code review. Now taking a look at you code again, this was not for you.

If you let me, i will advice you tu refactor a little bit the code. For example, in App.js you can extract all the cart logic into separate components to isolate concepts and functionality. Apply that at other parts, like the Home component. Here you can break it up in smaller pieces to be rehusable and the code always will be more readable. This will make the code more easy to test too, unit tests will be 'unit' tests. Apply SOLID principles is always a good approach.

You can close the issue :)

**Comment by Vhrollout** [comment]
I like constructive criticism, it helps me see broad picture. I'll
definitely implement what you have advised, i haven't planned before actual
coding that's created this mess. Thanks again.
